### ISSUE TITLE
在@Transactional的方法中切换数据源失败

### ISSUE THREAD

**Issue by ZhangKe4042602** [helloworlde/SpringBoot-DynamicDataSource#11]
数据源1是只读的权限，数据源2是读写的权限。在@Transactional的方法中切换数据，数据源切换的注解是在@service上添加的，并且注解切换数据源的操作也执行了，并且日志显示进行切换了。但是在执行sql时数据源还是没有切换。

**Comment by helloworlde** [comment]
README 最后的注意说了，当方法有 `@Transactional` 注解时无法切换数据源
