### ISSUE TITLE
测试数据的返回值

### ISSUE THREAD

**Issue by s1452583104** [helloworlde/SpringBoot-DynamicDataSource#12]
http://localhost:9999/product/1   分别返回几个从库的数据
http://localhost:9999/product    返回主库的数据

**Comment by helloworlde** [comment]
Thanks for your feedback, had fixed issue in 7f97b433aadecfa85945fec9cf5b8658e7be3c8a and 52169180a48226f4ec387f75f1779dbb67cf725c
