### ISSUE TITLE
Caused by: java.io.FileNotFoundException: class path resource [mapper/*.xml] cannot be opened because it does not exist

### ISSUE THREAD

**Issue by jiangxfsimon** [helloworlde/SpringBoot-DynamicDataSource#16]
我pull代码下来运行并且运行了，代码逻辑很清晰，而且代码精炼。但是发现了个小问题，始终会有找不到mapper/*.xml,下面是原来的配置。
@Bean
@ConfigurationProperties(prefix = "mybatis")
public SqlSessionFactoryBean sqlSessionFactoryBean() {
       ...........
     return sqlSessionFactoryBean;
}
在查看mybatis官网内容，其实不需要向spring容器中注入SqlSessionFactoryBean，只需要注入SqlSessionFactory就行，就不会有上面的问题了。截图是mybatis官网的解释(地址:http://mybatis.org/spring/zh/factorybean.html)。
![5](https://user-images.githubusercontent.com/42638986/78677592-81ae0f00-791a-11ea-9fef-d5187eda401b.png)

**Comment by helloworlde** [comment]
MyBatis 文档描述的是使用默认配置的情况下不需要，但是，这里需要设置属性和数据源，是需要 SqlSessionFactoryBean来实现的，SqlSessionFactory不能设置相关属性
另外，找不到 xml，可以修改 [DataSourceConfigurer.java#L118](https://github.com/helloworlde/SpringBoot-DynamicDataSource/blob/hikari/src/main/java/cn/com/hellowood/dynamicdatasource/configuration/DataSourceConfigurer.java#L118)配置，可以看下方法的注释内容
