### ISSUE TITLE
能否通过数据库表的方式来配置多个数据源？

### ISSUE THREAD

**Issue by smartdriver001** [helloworlde/SpringBoot-DynamicDataSource#2]
比如我有一个base库， 里面有一张表存放其他数据库的名称，用户，密码等，我想通过请求参数来来指定到其中的一个数据库，我应该怎么做？

**Comment by yosaku01** [comment]
http://blog.csdn.net/u011126891/article/details/79014741
这是我的解决方案，你看一下对你有帮助没有？

**Comment by helloworlde** [comment]
是可以的，也可以参考
[https://github.com/YHYR/Mybatis](https://github.com/YHYR/Mybatis)
[https://www.jianshu.com/p/4df0daa1cd68](https://www.jianshu.com/p/4df0daa1cd68)
实现，稍后会把这些加上去

**Comment by yosaku01** [comment]
用我的方案，MybatisHelper貌似会失效，可能需要调整MybatisHelper的代码

**Comment by huayanYu** [comment]
可以试试 https://github.com/baomidou/dynamic-datasource-spring-boot-starter

**Comment by gatspy** [comment]
我也蛮需要用类似，或者配置中心的方式实现多租户多库的数据源切换啊。怎么解呢？

**Comment by helloworlde** [comment]
> 我也蛮需要用类似，或者配置中心的方式实现多租户多库的数据源切换啊。怎么解呢？

可以用 SpringConfig +  SpringCloud Bus 实现，当配置更新之后通过 SpringCloud Bus 通知应用更新配置

**Comment by gatspy** [comment]
@helloworlde 谢谢您的回复。
更新配置应该不是问题。
在配置中心可以配置所有租户对应的数据库和数据源(目前是一个租户一个独立数据库)，然后从api接口中获取到当前租户的id后呢? 怎么配置来切换数据源？还有就是租户的读写分离呢？

**Comment by helloworlde** [comment]
@gatspy 
其实真正切换数据源的实现是通过修改当前线程的本地变量实现的，可以暴露 API 调用[切换数据源的方法](https://github.com/helloworlde/SpringBoot-DynamicDataSource/blob/master/src/main/java/cn/com/hellowood/dynamicdatasource/configuration/DynamicDataSourceContextHolder.java#L57)，读写分离也是通过设置不同的数据源Bean 名称，都可以使用这个方法来实现
