### ISSUE TITLE
springboot2.0+版本无法切换slave数据源。

### ISSUE THREAD

**Issue by fanglichun** [helloworlde/SpringBoot-DynamicDataSource#20]
见https://github.com/fanglichun/JAVA-000/tree/main/Week_07/DatabaseMasterSlave/v1.0

**Comment by helloworlde** [comment]
Please reference the document of [Issues](https://github.com/helloworlde/SpringBoot-DynamicDataSource/blob/master/Issues.md), and it works well if you follow the document.
