### ISSUE TITLE
后期再追加多个数据库的问题

### ISSUE THREAD

**Issue by codingKings** [helloworlde/SpringBoot-DynamicDataSource#21]
如果我想在这个多个数据库的springboot项目中，再追加多个数据库，能不能直接在配置文件yml中添加，而不用去改后台的java文件呢？？谢谢

**Comment by helloworlde** [comment]
可以读取配置文件动态生成 Bean,修改 [DataSourceConfigurer.java](https://github.com/helloworlde/SpringBoot-DynamicDataSource/blob/hikari/src/main/java/cn/com/hellowood/dynamicdatasource/configuration/DataSourceConfigurer.java) 的实现即可

**Comment by codingKings** [comment]
谢谢，改完DataSourceConfigurer.java文件确实可以动态生成Bean,在不改变后台程序的情况下，在properties配置文件可以随时增加数据库配置或者减少数据库配置数量，但是如果根据前端传进来的参数来确定使用的数据源的，是不是需要在DynamicDataSourceAspect.java文件的daoAspect()方法中来实现这个需求呢？

**Comment by helloworlde** [comment]
对 根据参数实现相应的选择逻辑，可以参考 [DynamicDataSourceAspect.java](https://github.com/helloworlde/SpringBoot-DynamicDataSource/blob/hikari/src/main/java/cn/com/hellowood/dynamicdatasource/configuration/DynamicDataSourceAspect.java#L67) 的逻辑实现；最终只要向 `CONTEXT_HOLDER` 中设置数据源的名称即可，参考 [DynamicDataSourceContextHolder.java](https://github.com/helloworlde/SpringBoot-DynamicDataSource/blob/c49b9b2e6e493917f6f0d7850ed69516d38c788c/src/main/java/cn/com/hellowood/dynamicdatasource/configuration/DynamicDataSourceContextHolder.java#L45)

**Comment by codingKings** [comment]
是的，还有个问题就是默认的连接池数现在好像是8个，这个是在哪里改写一下呢，比如我想默认的数据源连接池是20，谢谢

**Comment by codingKings** [comment]
谢谢，已经搞定了，配置的数据源的数量跟连接池没关系，已经实现了
![image](https://user-images.githubusercontent.com/38535538/102450272-fbcd9080-4070-11eb-94fa-6682fcf7e76f.png)
![image](https://user-images.githubusercontent.com/38535538/102450334-16076e80-4071-11eb-95e4-532f8a371f0e.png)
![image](https://user-images.githubusercontent.com/38535538/102450448-5ebf2780-4071-11eb-8d24-ad9c9589a4b0.png)
