### ISSUE TITLE
java: 无法将类 java.lang.ThreadLocal<T>中的方法 withInitial应用到给定类型

### ISSUE THREAD

**Issue by jiayb** [helloworlde/SpringBoot-DynamicDataSource#23]
private static final ThreadLocal<Object> CONTEXT_HOLDER = ThreadLocal.withInitial(DataSourceKey.master);

java: 无法将类 java.lang.ThreadLocal<T>中的方法 withInitial应用到给定类型;
  需要: java.util.function.Supplier<? extends S>
  找到: org.poem.enumeration.DataSourceKey
  原因: 无法推断类型变量 S
    (参数不匹配; org.poem.enumeration.DataSourceKey无法转换为java.util.function.Supplier<? extends S>)

报这个错

**Comment by helloworlde** [comment]
You can reference [DynamicDataSourceContextHolder.java#L27](https://github.com/helloworlde/SpringBoot-DynamicDataSource/blob/962b6d832cd78506f279ddc33535d9d6180f0661/src/main/java/cn/com/hellowood/dynamicdatasource/configuration/DynamicDataSourceContextHolder.java#L27)
