### ISSUE TITLE
在DAO上进行切片，没有办法切换数据库呀？ 只能在servcie

### ISSUE THREAD

**Issue by fanhualei** [helloworlde/SpringBoot-DynamicDataSource#4]
用master分支的代码，下载下来，无法切换数据库。 只能将Pointcut弄到service才可以，这是为什么？

@Pointcut("execution( * cn.com.hellowood.dynamicdatasource.mapper.*.*(..))")

**Comment by helloworlde** [comment]
```java
@Pointcut("execution( * cn.com.hellowood.dynamicdatasource.mapper.*.*(..))")
```
切面只对前缀为 `select` 的 DAO 层接口有效，代码是ok的
