### ISSUE TITLE
 where is the pom.xml

### ISSUE THREAD

**Issue by lengendary** [helloworlde/SpringBoot-DynamicDataSource#8]
I want to check out this project.But I didn't find the pom.xml.   Please help me ,thank u!

**Comment by helloworlde** [comment]
It's a Gradle project, you can build by `./gradlew clean build -x test` rather than Maven. Almost all IDE support Gradle also. You can find more information in [https://gradle.org/](https://gradle.org/)

**Comment by lengendary** [comment]
> It's a Gradle project, you can build by `./gradlew clean build -x test` rather than Maven. Almost all IDE support Gradle also. You can find more information in https://gradle.org/

Ok  ！ I will  search for it ! Thank u  very much!
